# Generated by Django 5.2.2 on 2025-09-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_company_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='employers.company'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
