# Generated by Django 5.2.2 on 2025-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='shortlist_instructions',
            field=models.TextField(blank=True, help_text='Instructions for shortlisted candidates', null=True),
        ),
    ]
