# Generated by Django 5.2.2 on 2025-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_currency',
            field=models.CharField(choices=[('NPR', 'Nepalese Rupee (NPR)'), ('USD', 'US Dollar (USD)'), ('GBP', 'British Pound (GBP)'), ('INR', 'Indian Rupee (INR)')], default='NPR', max_length=3),
        ),
    ]
