# Generated by Django 5.2.2 on 2025-09-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken'),
        ('jobs', '0002_add_currency_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsearch',
            options={'ordering': ['-searched_at']},
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobcategory'),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='accounts.jobseekerprofile'),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='query',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
