# Generated by Django 5.2.2 on 2025-09-02 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_careerpath_careermilestone_usercareerprogress_and_more'),
        ('employers', '0003_alter_employerprofile_company_and_more'),
        ('jobs', '0003_alter_jobsearch_options_jobsearch_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('click_through_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_metrics', to='jobs.jobpost')),
            ],
            options={
                'db_table': 'analytics_application_conversion',
            },
        ),
        migrations.CreateModel(
            name='CompanyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jobs_posted', models.PositiveIntegerField(default=0)),
                ('active_jobs', models.PositiveIntegerField(default=0)),
                ('total_applications_received', models.PositiveIntegerField(default=0)),
                ('total_hires', models.PositiveIntegerField(default=0)),
                ('avg_time_to_hire', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('company_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='employers.company')),
            ],
            options={
                'db_table': 'analytics_company_metrics',
            },
        ),
        migrations.CreateModel(
            name='EmployerEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_type', models.CharField(choices=[('job_post', 'Job Posted'), ('job_edit', 'Job Edited'), ('application_view', 'Application Viewed'), ('candidate_contact', 'Candidate Contacted'), ('job_promote', 'Job Promoted'), ('analytics_view', 'Analytics Viewed')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='employers.employerprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
            ],
            options={
                'db_table': 'analytics_employer_engagement',
                'indexes': [models.Index(fields=['employer', 'timestamp'], name='analytics_e_employe_d9c913_idx'), models.Index(fields=['engagement_type', 'timestamp'], name='analytics_e_engagem_0cca75_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('apply', 'Apply Button'), ('save', 'Save Job'), ('share', 'Share Job'), ('company_profile', 'Company Profile'), ('external_link', 'External Link')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_clicks', to='jobs.jobpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_job_click',
                'indexes': [models.Index(fields=['job', 'click_type', 'clicked_at'], name='analytics_j_job_id_afd0b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('search', 'Job Search'), ('filter', 'Apply Filter'), ('profile_update', 'Profile Update'), ('application_submit', 'Application Submitted'), ('job_save', 'Job Saved'), ('job_unsave', 'Job Unsaved')], max_length=20)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('filters_used', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.jobseekerprofile')),
            ],
            options={
                'db_table': 'analytics_jobseeker_activity',
                'indexes': [models.Index(fields=['job_seeker', 'timestamp'], name='analytics_j_job_see_dee5e0_idx'), models.Index(fields=['activity_type', 'timestamp'], name='analytics_j_activit_b30e52_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to='jobs.jobpost')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_job_view',
                'indexes': [models.Index(fields=['job', 'viewed_at'], name='analytics_j_job_id_79073a_idx'), models.Index(fields=['viewer', 'viewed_at'], name='analytics_j_viewer__2bd8bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('job_growth', 'Job Growth Rate'), ('salary_trend', 'Salary Trends'), ('skill_demand', 'Skill Demand'), ('location_hotspot', 'Location Hotspots'), ('industry_growth', 'Industry Growth')], max_length=20)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metric_label', models.CharField(max_length=100)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblocation')),
            ],
            options={
                'db_table': 'analytics_market_insight',
                'indexes': [models.Index(fields=['insight_type', 'created_at'], name='analytics_m_insight_d43f9e_idx'), models.Index(fields=['category', 'location'], name='analytics_m_categor_b92ac8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('experience_level', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_insight', to='jobs.jobpost')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.joblocation')),
            ],
            options={
                'db_table': 'analytics_salary_insight',
                'indexes': [models.Index(fields=['category', 'location'], name='analytics_s_categor_f9d43a_idx'), models.Index(fields=['experience_level', 'created_at'], name='analytics_s_experie_d822e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_demands', to='jobs.jobpost')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblocation')),
            ],
            options={
                'db_table': 'analytics_skill_demand',
                'indexes': [models.Index(fields=['skill_name', 'created_at'], name='analytics_s_skill_n_930dc4_idx'), models.Index(fields=['category', 'skill_name'], name='analytics_s_categor_165b29_idx')],
                'unique_together': {('skill_name', 'job', 'is_required')},
            },
        ),
        migrations.CreateModel(
            name='TrendingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('views', 'Most Viewed'), ('applications', 'Most Applied'), ('saves', 'Most Saved'), ('recent', 'Recently Posted'), ('urgent', 'Urgent Hiring')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rank', models.PositiveIntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_metrics', to='jobs.jobpost')),
            ],
            options={
                'db_table': 'analytics_trending_job',
                'indexes': [models.Index(fields=['trend_type', 'rank'], name='analytics_t_trend_t_9321b4_idx'), models.Index(fields=['created_at'], name='analytics_t_created_2952ab_idx')],
                'unique_together': {('job', 'trend_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('job_performance', 'Job Performance Alert'), ('skill_recommendation', 'Skill Recommendation'), ('market_trend', 'Market Trend Alert'), ('application_milestone', 'Application Milestone'), ('hiring_suggestion', 'Hiring Suggestion')], max_length=25)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_user_alert',
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='analytics_u_user_id_32c497_idx'), models.Index(fields=['alert_type', 'priority'], name='analytics_u_alert_t_28c458_idx')],
            },
        ),
    ]
