# Generated by Django 4.2.16 on 2025-09-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='target_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
