# Generated by Django 5.2.2 on 2025-09-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('education', 'Education'), ('engineering', 'Engineering'), ('design', 'Design'), ('sales', 'Sales'), ('operations', 'Operations'), ('consulting', 'Consulting')], max_length=50)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Comma-separated list of required skills')),
                ('average_salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('growth_outlook', models.CharField(blank=True, max_length=200, null=True)),
                ('education_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('milestone_type', models.CharField(choices=[('skill', 'Skill Development'), ('certification', 'Certification'), ('project', 'Project Completion'), ('experience', 'Work Experience'), ('education', 'Educational Achievement')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('estimated_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('resources', models.TextField(blank=True, help_text='Learning resources and links', null=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='accounts.careerpath')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserCareerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.careerpath')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_progress', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'career_path')},
            },
        ),
        migrations.CreateModel(
            name='CareerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('skill_test', 'Skill Test'), ('knowledge_quiz', 'Knowledge Quiz'), ('project_review', 'Project Review'), ('self_evaluation', 'Self Evaluation')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('score', models.IntegerField(blank=True, help_text='Score out of 100', null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.careermilestone')),
                ('user_career_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='accounts.usercareerprogress')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True, help_text='Link to portfolio, certificate, etc.', null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.careermilestone')),
                ('user_career_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_progress', to='accounts.usercareerprogress')),
            ],
            options={
                'unique_together': {('user_career_progress', 'milestone')},
            },
        ),
    ]
