# Generated by Django 5.2.6 on 2025-09-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_interviewanswer_interviewquestion_interviewanalytics_and_more'),
    ]

    operations = [
    ]
