# Generated by Django 5.2.6 on 2025-09-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_fix_resumeanalyticsreport_schema'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_passwordresetsession ADD COLUMN session_token VARCHAR(100) DEFAULT '';",
            reverse_sql="ALTER TABLE accounts_passwordresetsession DROP COLUMN session_token;"
        ),
        migrations.RunSQL(
            "ALTER TABLE accounts_passwordresetsession ADD COLUMN questions_answered_correctly INTEGER DEFAULT 0;",
            reverse_sql="ALTER TABLE accounts_passwordresetsession DROP COLUMN questions_answered_correctly;"
        ),
        migrations.RunSQL(
            "ALTER TABLE accounts_passwordresetsession ADD COLUMN is_verified BOOLEAN DEFAULT 0;",
            reverse_sql="ALTER TABLE accounts_passwordresetsession DROP COLUMN is_verified;"
        ),
        migrations.RunSQL(
            "ALTER TABLE accounts_passwordresetsession ADD COLUMN is_used BOOLEAN DEFAULT 0;",
            reverse_sql="ALTER TABLE accounts_passwordresetsession DROP COLUMN is_used;"
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX accounts_passwordresetsession_session_token_unique ON accounts_passwordresetsession(session_token);",
            reverse_sql="DROP INDEX accounts_passwordresetsession_session_token_unique;"
        ),
    ]
