# Generated by Django 5.2.6 on 2025-09-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20250917_0840'),
    ]

    operations = [
        migrations.RunSQL(
            # Add missing is_verified column
            "ALTER TABLE accounts_passwordresetsession ADD COLUMN is_verified BOOLEAN NOT NULL DEFAULT 0;",
            reverse_sql="ALTER TABLE accounts_passwordresetsession DROP COLUMN is_verified;"
        ),
        migrations.RunSQL(
            # Rename questions_answered to questions_answered_correctly
            """
            ALTER TABLE accounts_passwordresetsession RENAME COLUMN questions_answered TO questions_answered_correctly;
            """,
            reverse_sql=""" 
            ALTER TABLE accounts_passwordresetsession RENAME COLUMN questions_answered_correctly TO questions_answered;
            """
        ),
    ]
