# Generated by Django 5.2.6 on 2025-09-17 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20250917_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCareerRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_role', models.CharField(max_length=200)),
                ('target_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline_months', models.IntegerField(default=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roadmaps', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('step_type', models.CharField(choices=[('skill', 'Skill Development'), ('certification', 'Certification'), ('project', 'Project'), ('experience', 'Work Experience'), ('education', 'Education/Course'), ('networking', 'Networking'), ('milestone', 'Major Milestone'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('estimated_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('resources', models.TextField(blank=True, help_text='Links, courses, books, etc.', null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('success_criteria', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.customcareerroadmap')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='accounts.customroadmapstep')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
